resolver: lts-18.18

packages:
- 'digestive-functors-fn'
- 'fn-monadic'
- 'hspec-fn'

extra-deps:
- digestive-functors-0.8.4.2@sha256:badff1797b6dcd860a48ed4558985b2f6bec501e1016fa5afd9d7d6b0d8e4c08,3364

flags: {}

extra-package-dbs: []
