resolver: lts-13.6

packages:
- 'digestive-functors-fn'
- 'fn-monadic'

extra-deps:
- digestive-functors-0.8.4.2@sha256:badff1797b6dcd860a48ed4558985b2f6bec501e1016fa5afd9d7d6b0d8e4c08,3364
- git: https://github.com/positiondev/fn
  commit: a57e55c177e135db8097517fc81081274ad2d5c0
  subdirs:
    - fn
    - fn-extra

flags: {}

extra-package-dbs: []
